name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */2 * * *'   # every 2 hours

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Streamlit app
        run: |
          echo "Pinging factor-attribution.streamlit.app…"
          curl -fsS https://factor-attribution.streamlit.app/ || true
